name: Code test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python installation
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setting everything else
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
      - name: Run pytest
        run: python -m pytest --import-mode=append tests/